@baseUrl = http://localhost:8090/api/orders/


POST {{baseUrl}}
content-type: application/json

{
	"customer_id": "customer-123",
	"product": "demo-3",
	"price": 10.99,
	"quantity": 200

}


###

GET {{baseUrl}}
content-type: application/json


###

GET {{baseUrl}}cd9cfcad
content-type: application/json


###

GET {{baseUrl}}4d57078f
content-type: application/json


###

PUT {{baseUrl}}79cfd661/cancel
content-type: application/json

{
	"reason": "I don't want it anymore"
}


###

GET {{baseUrl}}events
content-type: application/json


