@baseUrl = http://localhost:8091/api/


POST {{baseUrl}}channels/
content-type: application/json

{
  "name": "demo2",
  "description": "A channel for testing purposes"
}


###

POST {{baseUrl}}subscriptions/channels/demo2
content-type: application/json

{
	"webhook_url": "https://9x1n96dg-8091.usw3.devtunnels.ms/webhook",
	"description": "A subscription for testing purposes"
}

###

POST {{baseUrl}}channels/demo2/publish
content-type: application/json

{
	"publisher_id": "test-publisher",
	"payload": "test-payload-4"
}
